### ISSUE TITLE
Breaking angular language server

### ISSUE THREAD

**Issue by richarddavenport** [arin-pang/ng9-odometer#1]
I'm not entirely sure of the issue, but the angular language server (I use it in VSCode) is bombing on the "styles" array in https://github.com/arin-pang/ng9-odometer/blob/master/projects/ng9-odometer/src/lib/ng9-odometer.component.ts#L30

**Comment by arin-pang** [comment]
Thanks for your report. I fixed this. I will publish the new version to NPM after testing includes other changes.

**Comment by richarddavenport** [comment]
Thanks!
